development:
  adapter: postgresql
  encoding: unicode
  database: demo_development
  pool: 5
  user: postgres
  host: localhost
  password: postgres

production:
  adapter: postgresql
  encoding: unicode
  database: demo_production
  pool: 5
  user: postgres
  password: postgres
  host: localhost